POST http://sap-killer.com/api/orders
Content-Type: application/json

{
    "uid": "2020000007",
    "user_id": 2,
    "agent_id": 2,
    "client_id": "3",
    "shop_id": "3",
    "deliverer_id": "1",
    "total": "116.5",
    "weight": "13",
    "warehouse_id": "1",
    "items": [
        {
            "id": 24,
            "user_id": "1",
            "order_id": "3",
            "item_id": 1,
            "qty": 32,
            "location_id": 1
        },
        {
            "id": 26,
            "order_id": "3",
            "item_id": 1,
            "qty": 24,
            "location_id": 1
        }
    ]
}