<?php

namespace Tests\Feature;

use App\Models\Client;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\Shop;
use App\Models\User;
use App\Models\Warehouse;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AgentCanCashInvoiceTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = User::factory()->create();
        $client = Client::factory()->create();
        $shop = Shop::factory()->create();
        $warehouse = Warehouse::factory()->create();
        $order = Order::factory()->create();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testExample()
    {
        $user = User::factory()->create(['role' => 'agent']);
        dump($user);
        $invoice = Invoice::factory()->create();

        $user->invoices->cash($invoice);
    }
}
